### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ShadowGaming100** [kabirsingh2004/JUGNU-MUSIC#1]
While pausing using emojis from play command

(node:643) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/runner/Fire-Music/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Fire-Music/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildMember.edit (/home/runner/Fire-Music/node_modules/discord.js/src/structures/GuildMember.js:312:5)
(node:643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: write EPIPE
ID: ghv5_c1dQh8
Name: Gearing Up for Glory
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}

Second error while running setup command 

(node:643) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/runner/Fire-Music/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Fire-Music/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Fire-Music/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by kabirsingh2004** [comment]
give bot perms
