### ISSUE TITLE
Playlist limit?

### ISSUE THREAD

**Issue by Sudo-null7** [kabirsingh2004/JUGNU-MUSIC#50]
Hi,

with this code the bot won't allow more then 100 songs in a playlist like:
https://open.spotify.com/playlist/0CDe8sRXL5SgXLXVH70EBk?si=179ee83e036e49eb
it outputs this to console

```
 [Error_Handling] :: Unhandled Rejection/Catch
TypeError [PlayError]: https://open.spotify.com/playlist/0CDe8sRXL5SgXLXVH70EBk?si=179ee83e036e49eb
Cannot read properties of undefined (reading '0')
    at SpotifyPlugin.play (/home/runner/JUGNU-MUSIC/node_modules/@distube/spotify/dist/index.js:183:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DisTube.play (/home/runner/JUGNU-MUSIC/node_modules/distube/dist/index.js:2229:13) Promise {
  <rejected> TypeError [PlayError]: https://open.spotify.com/playlist/0CDe8sRXL5SgXLXVH70EBk?si=179ee83e036e49eb
  Cannot read properties of undefined (reading '0')
      at SpotifyPlugin.play (/home/runner/JUGNU-MUSIC/node_modules/@distube/spotify/dist/index.js:183:36)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async DisTube.play (/home/runner/JUGNU-MUSIC/node_modules/distube/dist/index.js:2229:13)
}
```

Can you fix this problem as other bots can do more then this

**Comment by Sudo-null7** [comment]
it doesn't work with any type of spotify playlist links

**Comment by kabirsingh2004** [comment]
its working now try

https://media.discordapp.net/attachments/1048976771137147002/1074020521211076688/Screenshot_2023-02-11_230326.png
