### ISSUE TITLE
not creating / commands

### ISSUE THREAD

**Issue by Dhyanpatelhaker** [kabirsingh2004/JUGNU-MUSIC#6]

**Comment by Dhyanpatelhaker** [comment]
at async GuildApplicationCommandManager.set (/Users/Mymacbook/Downloads/JUGNU-MUSIC-main/node_modules/discord.js/src/managers/ApplicationCommandManager.js:145:18)
    at async /Users/Mymacbook/Downloads/JUGNU-MUSIC-main/handlers/slash_handler.js:46:11 {
  method: 'put',
  path: '/applications/880092626198618183/guilds/877432976844136458/commands',
  code: 50001,
  httpStatus: 403,
  requestData: {
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ],
    files: []
  }
}
DiscordAPIError: Missing Access
    at RequestHandler.execute (/Users/Mymacbook/Downloads/JUGNU-MUSIC-main/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/Mymacbook/Downloads/JUGNU-MUSIC-main/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async GuildApplicationCommandManager.set (/Users/Mymacbook/Downloads/JUGNU-MUSIC-main/node_modules/discord.js/src/managers/ApplicationCommandManager.js:145:18)
    at async /Users/Mymacbook/Downloads/JUGNU-MUSIC-main/handlers/slash_handler.js:46:11 {
  method: 'put',
  path: '/applications/880092626198618183/guilds/908750107887943750/commands',
  code: 50001,
  httpStatus: 403,
  requestData: {
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ],
    files: []
  }
}

**Comment by kabirsingh2004** [comment]
fixed now try

**Comment by CoolMusic1** [comment]
Use Now Again 
Thanks
