### ISSUE TITLE
Getting Error on mongodb 

### ISSUE THREAD

**Issue by BlackBox-cmd** [kabirsingh2004/JUGNU-MUSIC#66]
Os: linux

` [Error_Handling] :: Unhandled Rejection/Catch
MongoError: database names cannot contain the character ' '
    at MongoError.create (/home/container/node_modules/mongodb/lib/core/error.js:59:12)
    at validateDatabaseName (/home/container/node_modules/mongodb/lib/operations/db_ops.js:351:24)
    at new Db (/home/container/node_modules/mongodb/lib/db.js:193:3)
    at MongoClient.db (/home/container/node_modules/mongodb/lib/mongo_client.js:379:14)
    at JoshProvider.init (/home/container/node_modules/@joshdb/mongo/src/index.js:40:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  driver: true
} Promise {
  <rejected> MongoError: database names cannot contain the character ' '
      at MongoError.create (/home/container/node_modules/mongodb/lib/core/error.js:59:12)
      at validateDatabaseName (/home/container/node_modules/mongodb/lib/operations/db_ops.js:351:24)
      at new Db (/home/container/node_modules/mongodb/lib/db.js:193:3)
      at MongoClient.db (/home/container/node_modules/mongodb/lib/mongo_client.js:379:14)
      at JoshProvider.init (/home/container/node_modules/@joshdb/mongo/src/index.js:40:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    driver: true
  }
}
 [Error_Handling] :: Unhandled Rejection/Catch
MongoError: database names cannot contain the character ' '
    at MongoError.create (/home/container/node_modules/mongodb/lib/core/error.js:59:12)
    at validateDatabaseName (/home/container/node_modules/mongodb/lib/operations/db_ops.js:351:24)
    at new Db (/home/container/node_modules/mongodb/lib/db.js:193:3)
    at MongoClient.db (/home/container/node_modules/mongodb/lib/mongo_client.js:379:14)
    at JoshProvider.init (/home/container/node_modules/@joshdb/mongo/src/index.js:40:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  driver: true
} Promise {
  <rejected> MongoError: database names cannot contain the character ' '
      at MongoError.create (/home/container/node_modules/mongodb/lib/core/error.js:59:12)
      at validateDatabaseName (/home/container/node_modules/mongodb/lib/operations/db_ops.js:351:24)
      at new Db (/home/container/node_modules/mongodb/lib/db.js:193:3)
      at MongoClient.db (/home/container/node_modules/mongodb/lib/mongo_client.js:379:14)
      at JoshProvider.init (/home/container/node_modules/@joshdb/mongo/src/index.js:40:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    driver: true
  }
}`

**Comment by kabirsingh2004** [comment]
This is an unhandled rejection error caused by attempting to use a database name with a space character (' '). Ensure database names do not contain spaces, and handle this error to prevent it from crashing your application.
